(() => {
  const $ = s => document.querySelector(s); const tokenKey = 'ef_staff_token'; let token = sessionStorage.getItem(tokenKey); let role = sessionStorage.getItem('ef_staff_role') || ''; let products = []; const manualItems = new Map();
  const money = cents => `S/ ${(Number(cents || 0) / 100).toFixed(2)}`;
  const request = async (path, options = {}) => { const response = await fetch(`/api${path}`, { ...options, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'No se pudo completar la operación.'); return data; };
  function toast(message) { const node = $('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); }
  function setRole(next) { role = next; $('#loginView').hidden = true; $('#staffView').hidden = false; $('#roleLabel').textContent = next === 'admin' ? 'Administrador' : 'Mesero'; $('#welcomeTitle').textContent = next === 'admin' ? 'Operación del local' : 'Pedidos'; document.querySelectorAll('[data-admin]').forEach(el => { el.hidden = next !== 'admin'; }); }
  $('#loginForm').addEventListener('submit', async e => { e.preventDefault(); $('#loginError').textContent = ''; try { const session = await request('/login', { method: 'POST', body: JSON.stringify({ email: $('#loginEmail').value, password: $('#loginPassword').value }) }); token = session.accessToken; role = session.role; sessionStorage.setItem(tokenKey, token); sessionStorage.setItem('ef_staff_role', role); setRole(role); await loadAll(); } catch (err) { $('#loginError').textContent = err.message; } });
  $('#logout').addEventListener('click', () => { token = null; sessionStorage.removeItem(tokenKey); $('#staffView').hidden = true; $('#loginView').hidden = false; });
  async function loadProducts() { products = await request(role === 'admin' ? '/staff/products' : '/catalog'); const select = $('#manualProduct'); select.replaceChildren(); products.filter(p => p.available).forEach(p => { const opt = document.createElement('option'); opt.value = p.catalog_key; opt.textContent = `${p.name} · ${money(p.price_cents)}`; select.append(opt); }); if (role === 'admin') renderProducts(); }
  function renderProducts() { const root = $('#productsList'); root.replaceChildren(); for (const p of products) { const row = document.createElement('div'); row.className = 'product-row'; const info = document.createElement('span'); info.textContent = `${p.name} · ${p.category} · ${money(p.price_cents)}${p.available ? '' : ' · Agotado'}`; const button = document.createElement('button'); button.textContent = p.available ? 'Marcar agotado' : 'Activar'; button.className = 'secondary'; button.addEventListener('click', async () => { try { await request('/staff/products', { method: 'POST', body: JSON.stringify({ ...p, available: !p.available }) }); toast('Disponibilidad actualizada.'); await loadProducts(); } catch (e) { toast(e.message); } }); row.append(info, button); root.append(row); } }
  function statusLabel(status) { return ({ pending: 'Pendiente', accepted: 'Aceptado', preparing: 'En preparación', ready: 'Listo', delivered: 'Entregado', paid: 'Pagado', cancelled: 'Anulado' })[status] || status; }
  function renderOrders(orders) { const root = $('#ordersList'); root.replaceChildren(); if (!orders?.length) { root.innerHTML = '<p class="empty">No hay pedidos activos.</p>'; return; } for (const order of orders) { const card = document.createElement('article'); card.className = 'order-card'; const head = document.createElement('div'); head.className = 'order-card-head'; const title = document.createElement('div'); const h = document.createElement('h3'); h.textContent = `Pedido ${order.code ? `#${order.code}` : ''}`.trim(); const meta = document.createElement('p'); meta.textContent = `${order.table_number ? `Mesa ${order.table_number} · ` : 'Sin mesa · '}${new Date(order.created_at).toLocaleString('es-PE')}`; const status = document.createElement('span'); status.className = 'status'; status.textContent = statusLabel(order.status); title.append(h, meta); head.append(title, status); card.append(head);
      const list = document.createElement('ul'); for (const item of order.items || []) { const li = document.createElement('li'); li.textContent = `${item.quantity} × ${item.name || item.product_name}${item.note ? ` — ${item.note}` : ''}`; list.append(li); } card.append(list); const total = document.createElement('strong'); total.textContent = `Total ${money(order.total_cents)}`; card.append(total);
      const actions = document.createElement('div'); actions.className = 'order-card-actions';
      if (order.status === 'pending') addAction(actions, 'Aceptar', () => action({ action: 'transition', orderId: order.id, status: 'accepted' }));
      const table = document.createElement('select'); table.setAttribute('aria-label', 'Asignar mesa'); const opt = document.createElement('option'); opt.value = ''; opt.textContent = 'Asignar mesa'; table.append(opt); for (let i = 1; i <= 20; i++) { const op = document.createElement('option'); op.value = String(i); op.textContent = `Mesa ${i}`; op.selected = order.table_number === i; table.append(op); } table.addEventListener('change', () => table.value && action({ action: 'assign-table', orderId: order.id, tableNumber: Number(table.value) })); if (!['paid','cancelled'].includes(order.status)) actions.append(table);
      const next = ({ accepted: ['preparing','Iniciar preparación'], preparing: ['ready','Marcar listo'], ready: ['delivered','Entregado'] })[order.status]; if (next) addAction(actions, next[1], () => action({ action: 'transition', orderId: order.id, status: next[0] }));
      if (order.table_number && !['cancelled','pending'].includes(order.status)) addAction(actions, `Imprimir comanda${order.print_count ? ` (reimpresión ${order.print_count})` : ''}`, () => printTicketAfterRecord(order));
      if (role === 'admin' && order.status === 'delivered') { const pay = document.createElement('select'); pay.innerHTML = '<option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option>'; actions.append(pay); addAction(actions, 'Cobrar', () => action({ action: 'pay', orderId: order.id, payments: [{ amountCents: order.total_cents, method: pay.value }] })); }
      if (role === 'admin' && !['paid','cancelled'].includes(order.status)) addAction(actions, 'Anular', async () => { const reason = prompt('Motivo de anulación:'); if (reason) action({ action: 'transition', orderId: order.id, status: 'cancelled', reason }); });
      card.append(actions); root.append(card); } }
  function addAction(parent, label, callback) { const button = document.createElement('button'); button.type = 'button'; button.textContent = label; button.addEventListener('click', callback); parent.append(button); }
  async function loadOrders() { try { renderOrders(await request('/staff/orders')); } catch (e) { $('#orderNotice').textContent = e.message; } }
  async function action(data) { try { await request('/staff/orders/action', { method: 'POST', body: JSON.stringify(data) }); $('#orderNotice').textContent = 'Pedido actualizado.'; await loadOrders(); } catch (e) { $('#orderNotice').textContent = e.message; } }
  $('#refreshOrders').addEventListener('click', loadOrders);
  $('#searchCode').addEventListener('click', async () => { const code = $('#codeSearch').value.trim(); if (!/^\d{4}$/.test(code)) { $('#orderNotice').textContent = 'Ingresa los cuatro dígitos.'; return; } try { const order = await request(`/staff/orders?code=${encodeURIComponent(code)}`); renderOrders(order ? [order] : []); $('#orderNotice').textContent = order ? 'Pedido encontrado.' : 'No hay un pedido vigente con ese código.'; } catch (e) { $('#orderNotice').textContent = e.message; } });
  for (let i = 1; i <= 20; i++) { const option = document.createElement('option'); option.value = String(i); option.textContent = `Mesa ${i}`; $('#manualTable').append(option); }
  $('#manualForm').addEventListener('submit', async e => { e.preventDefault(); const product = products.find(p => p.catalog_key === $('#manualProduct').value); if (!product) return; try { await request('/staff/orders', { method: 'POST', body: JSON.stringify({ tableNumber: Number($('#manualTable').value), items: [{ productId: product.catalog_key, quantity: Number($('#manualQuantity').value), notes: '' }] }) }); toast('Pedido registrado.'); await loadOrders(); } catch (err) { toast(err.message); } });
  async function printTicketAfterRecord(order) { try { await request('/staff/orders/action', { method:'POST', body:JSON.stringify({action:'print',orderId:order.id}) }); printTicket(order); await loadOrders(); } catch(e) { toast(e.message); } }
  function printTicket(order) { const ticket = window.open('', '_blank', 'width=380,height=620'); if (!ticket) { toast('Permite ventanas emergentes para imprimir.'); return; } const lines = (order.items || []).map(item => `<li>${item.quantity} × ${escapeHtml(item.name || item.product_name)}${item.note ? `<small>${escapeHtml(item.note)}</small>` : ''}</li>`).join(''); ticket.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Comanda</title><style>body{font:16px monospace;width:72mm;margin:4mm}h1{text-align:center;font-size:20px}hr{border:0;border-top:1px dashed}li{margin:10px 0}small{display:block;margin-left:8px}footer{text-align:center;margin-top:20px}</style></head><body><h1>ESTACIÓN FRUTAL</h1><hr><p>Pedido: ${escapeHtml(order.code || order.id.slice(0,8))}<br>MESA: ${order.table_number}<br>${new Date(order.created_at).toLocaleString('es-PE')}</p><hr><ul>${lines}</ul><hr><footer>Comanda de preparación</footer><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`); ticket.document.close(); }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])); }
  async function loadStaff() { const rows=await request('/staff/users'); const root=$('#staffList'); root.replaceChildren(); for(const user of rows){const row=document.createElement('div');row.className='product-row';const info=document.createElement('span');info.textContent=`${user.email||user.id} · ${user.active?'Activa':'Desactivada'}`;row.append(info);if(user.role==='waiter'){const toggle=document.createElement('button');toggle.className='secondary';toggle.textContent=user.active?'Desactivar':'Activar';toggle.addEventListener('click',async()=>{try{await request('/staff/users',{method:'POST',body:JSON.stringify({action:user.active?'deactivate':'activate',userId:user.id})});toast('Cuenta actualizada.');await loadStaff();}catch(e){toast(e.message);}});const reset=document.createElement('button');reset.className='secondary';reset.textContent='Restablecer contraseña';reset.addEventListener('click',async()=>{const password=prompt('Nueva contraseña (12 caracteres mínimo):');if(!password)return;try{await request('/staff/users',{method:'POST',body:JSON.stringify({action:'reset-password',userId:user.id,password})});toast('Contraseña restablecida.');}catch(e){toast(e.message);}});row.append(toggle,reset);}root.append(row);} }
  async function loadCash() { try { const session = await request('/staff/cash'); $('#cashState').textContent = session ? `Caja abierta · Inicial ${money(session.opening_cents)}` : 'No hay una caja abierta.'; $('#openCashForm').hidden = !!session; $('#closeCashForm').hidden = !session; $('#closeCashForm').dataset.sessionId = session?.id || ''; } catch (e) { $('#cashState').textContent = e.message; } }
  $('#openCashForm').addEventListener('submit', async e => { e.preventDefault(); try { await request('/staff/orders/action', { method: 'POST', body: JSON.stringify({ action: 'open-cash', amountCents: Math.round(Number($('#openingAmount').value) * 100) }) }); toast('Caja abierta.'); await loadCash(); } catch (err) { toast(err.message); } });
  $('#closeCashForm').addEventListener('submit', async e => { e.preventDefault(); try { const result = await request('/staff/orders/action', { method: 'POST', body: JSON.stringify({ action: 'close-cash', sessionId: e.currentTarget.dataset.sessionId, countedCents: Math.round(Number($('#countedAmount').value) * 100), note: $('#cashNote').value }) }); toast(`Caja cerrada · Diferencia ${money(result.difference_cents)}`); await loadCash(); } catch (err) { toast(err.message); } });
  $('#loadSales').addEventListener('click', async () => { const from = $('#salesFrom').value ? `${$('#salesFrom').value}T00:00:00-05:00` : ''; const to = $('#salesTo').value ? `${$('#salesTo').value}T23:59:59-05:00` : ''; try { const data = await request(`/staff/sales?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); const root=$('#salesSummary'); root.replaceChildren(); const count=document.createElement('p'); count.textContent=`${data.orders||0} pedidos pagados`; const total=document.createElement('p'); total.className='sales-total'; total.textContent=money(data.totalCents); root.append(count,total); const methods={cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',other:'Otro'}; for(const [method,cents] of Object.entries(data.byMethod||{})){const row=document.createElement('p');row.textContent=`${methods[method]||method}: ${money(cents)}`;root.append(row);} } catch (e) { $('#salesSummary').textContent = e.message; } });
  $('#productForm').addEventListener('submit', async e => { e.preventDefault(); const name = $('#productName').value.trim(), category = $('#productCategory').value.trim(); const slug = value => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); const categoryKey = [...document.querySelectorAll('.category')].find(section=>section.querySelector('h2')?.textContent.trim()===category)?.id || slug(category); try { await request('/staff/products', { method: 'POST', body: JSON.stringify({ catalog_key: `${categoryKey}-${slug(name)}`, name, category, description: $('#productDescription').value, price_cents: Math.round(Number($('#productPrice').value) * 100), available: true }) }); toast('Producto guardado.'); e.currentTarget.reset(); await loadProducts(); } catch (err) { toast(err.message); } });
  $('#userForm').addEventListener('submit', async e => { e.preventDefault(); try { await request('/staff/users', { method: 'POST', body: JSON.stringify({ email: $('#staffEmail').value, password: $('#staffPassword').value, role: 'waiter' }) }); $('#userNotice').textContent = 'Cuenta de mesero creada.'; e.currentTarget.reset(); } catch (err) { $('#userNotice').textContent = err.message; } });
  document.querySelectorAll('#tabs button').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('#tabs button').forEach(b => b.classList.toggle('active', b === button)); document.querySelectorAll('.view').forEach(v => v.hidden = v.id !== `${button.dataset.view}View`); }));
  async function loadAll() { try { await loadProducts(); await loadOrders(); if (role === 'admin') await loadCash(); } catch (e) { toast(e.message); } }
  if (token) { request('/staff/orders').then(() => { setRole(role || 'waiter'); loadAll(); }).catch(() => { sessionStorage.removeItem(tokenKey); token = null; }); }
  setInterval(() => { if (token && !$('#staffView').hidden) loadOrders(); }, 8000);
})();







