-- Generated from index.html by scripts/generate-seed.mjs. Re-run after editing the menu.
insert into public.products(catalog_key,name,category,description,price_cents,image_url) values
('jugos-clasicos-fresa','Fresa','Jugos Clásicos','',1000,'img/jugos_clasicos/fresa.png'),
('jugos-clasicos-papaya','Papaya','Jugos Clásicos','',900,'img/jugos_clasicos/papaya.png'),
('jugos-clasicos-pina','Piña','Jugos Clásicos','',900,'img/jugos_clasicos/pina.png'),
('jugos-clasicos-surtido','Surtido','Jugos Clásicos','',900,'img/jugos_clasicos/surtido.png'),
('jugos-clasicos-mango','Mango','Jugos Clásicos','',1000,'img/jugos_clasicos/mango.png'),
('jugos-clasicos-naranja','Naranja','Jugos Clásicos','',1000,'img/jugos_clasicos/naranja.png'),
('jugos-clasicos-maracuya','Maracuyá','Jugos Clásicos','',1000,'img/jugos_clasicos/maracuya.png'),
('jugos-clasicos-guanabana','Guanábana','Jugos Clásicos','',1000,'img/jugos_clasicos/guanabana.png'),
('jugos-leche-arandano-fresa-mango-y-leche','Arándano, fresa, mango y leche','Jugos con Leche','',1500,'img/jugos_con_leche/arandano_fresa_mango_leche.png'),
('jugos-leche-arandano-fresa-y-leche','Arándano, fresa y leche','Jugos con Leche','',1500,''),
('jugos-leche-arandano-y-leche','Arándano y leche','Jugos con Leche','',1400,'img/jugos_con_leche/arandano_leche.png'),
('jugos-leche-fresa-con-leche','Fresa con leche','Jugos con Leche','',1300,'img/jugos_con_leche/fresa_leche.png'),
('jugos-leche-mango-con-leche','Mango con leche','Jugos con Leche','',1300,'img/jugos_con_leche/mango_leche.png'),
('jugos-leche-platano-con-leche','Plátano con leche','Jugos con Leche','',1000,'img/jugos_con_leche/platano_leche.png'),
('jugos-leche-lucuma-con-leche','Lúcuma con leche','Jugos con Leche','',1400,'img/jugos_con_leche/lucuma_leche.png'),
('jugos-leche-guanabana-con-leche','Guanábana con leche','Jugos con Leche','',1400,'img/jugos_con_leche/guanabana_leche.png'),
('jugos-leche-papaya-con-leche','Papaya con leche','Jugos con Leche','',1200,'img/jugos_con_leche/papaya_leche.png'),
('jugos-leche-especial','Especial','Jugos con Leche','',1200,'img/jugos_con_leche/especial.png'),
('frappes-frappe-oreo','Frappe Oreo','Frappes','',1300,'img/frappes/frappe_oreo.png'),
('frappes-frappe-caramelo','Frappe caramelo','Frappes','',1300,'img/frappes/frappe_caramelo.png'),
('frappes-frappe-moka','Frappe moka','Frappes','',1300,'img/frappes/frappe_moka.png'),
('frappes-frappe-de-coco','Frappe de coco','Frappes','',1300,'img/frappes/frappe_coco.png'),
('frappes-frappe-fresa-con-leche','Frappe fresa con leche','Frappes','',1300,'img/frappes/frappe_fresa_leche.png'),
('frappes-frappe-arandano-con-leche','Frappe arándano con leche','Frappes','',1400,'img/frappes/frappe_arandano_leche.png'),
('frozen-maracumango-frozen','Maracumango frozen','Frozen','',1500,'img/frozen/frozen_maracumango.png'),
('frozen-pina-frozen','Piña frozen','Frozen','Limón y Jamaica',1200,'img/frozen/frozen_pina.png'),
('cafe-cafe-clasico','Café clásico','Café','',600,'img/cafe/cafe_clasico.png'),
('cafe-capuchino-con-chantilly','Capuchino con chantilly','Café','Dulce',1000,'img/cafe/capuccino_chantilly.png'),
('cafe-chocolate-con-leche','Chocolate con leche','Café','',1000,'img/cafe/chocolate_leche.png'),
('infusiones-infusion-de-jamaica','Infusión de Jamaica','Infusiones','Flor de Jamaica y canela',800,'img/cafe/infusion_jamaica.png'),
('sandwich-sandwich-clasico','Sándwich clásico','Sándwich','Pollo, jamón, queso',1200,'img/sandwich/sandwich_clasico.png'),
('sandwich-sandwich-mixto','Sándwich mixto','Sándwich','Pollo, lechuga, huevo',1100,'img/sandwich/sandwich_mixto.png'),
('sandwich-club-sandwich','Club sándwich','Sándwich','3 capas de pan, tocino, pollo, queso, jamón, huevo, lechuga, tomate, papas al hilo',2000,'img/sandwich/club_sandwich.png'),
('hamburguesas-hamburguesa-simple','Hamburguesa simple','Hamburguesas','Carne, tomate, lechuga, papitas al hilo',800,'img/hamburguesas/hamburguesa_simple.png'),
('hamburguesas-hamburguesa-royal','Hamburguesa Royal','Hamburguesas','Carne, huevo, queso, tomate, lechuga, papitas al hilo',1200,'img/hamburguesas/hamburguesa_royal.png'),
('hamburguesas-hamburguesa-mixta','Hamburguesa mixta','Hamburguesas','Carne, pollo, huevo, tomate, lechuga, papitas al hilo',1200,'img/hamburguesas/hamburguesa_mixta.png'),
('hamburguesas-pan-con-pollo','Pan con pollo','Hamburguesas','Pollo deshilachado, lechuga, papitas al hilo',900,'img/hamburguesas/pan_con_pollo.png'),
('hamburguesas-hamburguesa-finolis','Hamburguesa Finolis','Hamburguesas','Carne, huevo, doble queso, tocino, tomate, lechuga, papitas al hilo',1500,'img/hamburguesas/hamburguesa_finolis.png'),
('empanadas-empanada-de-pollo','Empanada de pollo','Empanadas','',600,'img/empanadas/empanada_pollo.png'),
('empanadas-empanada-de-carne','Empanada de carne','Empanadas','',600,'img/empanadas/empanada_carne.png'),
('empanadas-empanada-jamon-con-queso','Empanada jamón con queso','Empanadas','',600,'img/empanadas/empanada_jamon_queso.png'),
('ensaladas-ensalada-de-fruta','Ensalada de fruta','Ensalada de Fruta','',1200,'img/ensaladas/ensalada_fruta.png'),
('postres-cheesecake-de-maracuya','Cheesecake de maracuyá','Postres','',1000,'img/postres/cheesecake_maracuya.png'),
('postres-cheesecake-de-fresa','Cheesecake de fresa','Postres','',1000,'img/postres/cheesecake_fresa.png'),
('postres-cheesecake-de-arandano','Cheesecake de arándano','Postres','',1000,'img/postres/cheesecake_arandano.png'),
('postres-crema-volteada','Crema volteada','Postres','',1000,'img/postres/crema_volteada.png'),
('postres-keke-de-naranja','Keke de naranja','Postres','',400,''),
('postres-keke-de-vainilla','Keke de vainilla','Postres','Con chispas de chocolate',400,'img/postres/keke_vainilla.png'),
('rollos-rollo-con-arandanos','Rollo con arándanos','Rollos de Canela','',1000,'img/rollos/rollito_arandano.png'),
('rollos-rollo-con-pecanas','Rollo con pecanas','Rollos de Canela','',1000,'img/rollos/rollito_pecanas.png')
on conflict (catalog_key) do update set name=excluded.name,category=excluded.category,description=excluded.description,price_cents=excluded.price_cents,image_url=excluded.image_url,updated_at=now();
